ITCompany/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ITCompany.Data;
using ITCompany.Models;

namespace ITCompany.Controllers
{
    public class RolesController : Controller
    {
        private readonly ITCompanyContext _context;

        public RolesController(ITCompanyContext context)
        {
            _context = context;
        }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync()); 
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.ID == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] Role role)
        {
            if (id != role.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.ID == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Roles.FindAsync(id);
            _context.Roles.Remove(role);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
            return _context.Roles.Any(e => e.ID == id);
        }
    }
}

ITCompany/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ITCompany.Data;
using ITCompany.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace ITCompany.Controllers
{
    public class UsersController : Controller
    {
        private readonly ITCompanyContext _context;
        private IHostingEnvironment Environment;

        public UsersController(ITCompanyContext context, IHostingEnvironment _environment)
        {
            _context = context;
            Environment = _environment;        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            var iTCompanyContext = _context.Users.Include(u => u.Role);
            return View(await iTCompanyContext.ToListAsync());
        } 


        // GET: Clients
        public async Task<IActionResult> Clients()
        {
            var iTCompanyContext = _context.Users.Include(u => u.Role).Where(x=>x.RoleID == _context.Roles.First(x=>x.Name.Equals("Клієнт")).ID);
            return View("Index", await iTCompanyContext.ToListAsync());
        }
        // GET: Employees
        public async Task<IActionResult> Employees()
        {
            var iTCompanyContext = _context.Users.Include(u => u.Role).Where(x => x.RoleID != _context.Roles.First(x => x.Name.Equals("Клієнт")).ID);
            return View("Index", await iTCompanyContext.ToListAsync());
        }


        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                ViewBag.My = true;
                var currentUser = _context.Users
                    .Include(x => x.Role)
                    .Include(x => x.Projects)
                    .Include(u => u.ProjectCommands)
                    .Include(x => x.TaskCommands)
                    .First(x => x.Login.Equals(HttpContext.User.Identity.Name));
                foreach (Project p in currentUser.Projects)
                {
                    p.ProjectType = _context.ProjectTypes.First(x => x.ID == p.ProjectTypeID);
                }
                foreach (ProjectCommand pc in currentUser.ProjectCommands)
                {
                    pc.Project = _context.Projects.Include(x=>x.ProjectType).Include(x => x.Tasks).Include(x=>x.ProjectCommands).First(x => x.ID == pc.ProjectID);
                }
                foreach (TaskCommand tc in currentUser.TaskCommands)
                {
                    tc.Task = _context.Tasks.Include(x => x.Project).First(x => x.ID == tc.TaskID);
                }

                return View(currentUser);
            }

            ViewBag.My = false;
            var user = await _context.Users
                .Include(u => u.Role)
                .Include(x => x.Projects)
                    .Include(u => u.ProjectCommands)
                    .Include(x => x.TaskCommands)
                .FirstOrDefaultAsync(m => m.ID == id);

            foreach (Project p in user.Projects)
            {
                p.ProjectType = _context.ProjectTypes.First(x => x.ID == p.ProjectTypeID);
            }
            foreach (ProjectCommand pc in user.ProjectCommands)
            {
                pc.Project = _context.Projects.Include(x => x.ProjectType).Include(x=>x.Tasks).Include(x => x.ProjectCommands).First(x => x.ID == pc.ProjectID);
            }
            foreach (TaskCommand tc in user.TaskCommands)
            {
                tc.Task = _context.Tasks.Include(x=>x.Project).First(x => x.ID == tc.TaskID);
            }

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            ViewData["RoleID"] = new SelectList(_context.Roles, "ID", "Name");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Login,Password,FirstName,LastName,RoleID")] User user, IFormFile file)
        {

            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();

                string wwwPath = this.Environment.WebRootPath;
                string contentPath = this.Environment.ContentRootPath;

                User user2 = _context.Users.First(x => x.Login.Equals(user.Login));

                string path = Path.Combine(this.Environment.WebRootPath, "Images/Users/" + user2.ID);
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                string fileName = Path.GetFileName(file.FileName);
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                user2.Avatar = "/Images/Users/" + user2.ID + "/" + fileName;

                _context.Users.Update(user2);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleID"] = new SelectList(_context.Roles, "ID", "Name", user.RoleID);
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["RoleID"] = new SelectList(_context.Roles, "ID", "Name", user.RoleID);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Login,Password,FirstName,LastName,Avatar,RoleID")] User user, IFormFile file)
        {
            if (id != user.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        string wwwPath = this.Environment.WebRootPath;
                        string contentPath = this.Environment.ContentRootPath;

                        string path = Path.Combine(this.Environment.WebRootPath, "Images/Users/" + user.ID);
                        if (!Directory.Exists(path))
                        {
                            Directory.CreateDirectory(path);
                        }

                        string fileName = Path.GetFileName(file.FileName);
                        using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                        {
                            file.CopyTo(stream);
                        }

                        user.Avatar = "/Images/Users/" + user.ID + "/" + fileName;
                    }
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect("~/Users/Details/" + user.ID);
            }
            ViewData["RoleID"] = new SelectList(_context.Roles, "ID", "Name", user.RoleID);
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.ID == id);
        }
    }
}

ITCompany/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ITCompany</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ITCompany</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if(User.Identity.IsAuthenticated)
                        {
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Головна</a>
                            </li>

                            if(User.IsInRole("Директор"))
                            {
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Clients">Клієнти</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Employees">Працівники</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Посади</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Проєкти</a>
                                </li>
                            }

                            if(User.IsInRole("Клієнт"))
                            {
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="MyProjects">Проекти</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Create">Створити проект</a>
                                </li>
                            }
                            if(User.IsInRole("HR Manager"))
                            {
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Employees">Працівники</a>
                                </li>
                            }
                            if(!User.IsInRole("HR Manager") && !User.IsInRole("Клієнт") && !User.IsInRole("Директор"))
                            {
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="MyProjects">Мої проєкти</a>
                                </li>
                            }
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Details">Мій профіль</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Вийти</a>
                            </li>
                        }
                        else
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Логін</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Реєстрація</a>
                                </li>
                            </ul>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ITCompany - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>