ITCompany/Models/Task.cs
using System;
using System.Collections.Generic;

namespace ITCompany.Models
{
    public class Task
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public DateTime FactDate { get; set; }
        public string Description { get; set; }
        public int Coeffecient { get; set; }
        public int ProjectID { get; set; }
        public Project Project { get; set; } 
        public ICollection<TaskCommand> TaskCommands { get; set; }
    }
}

ITCompany/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ITCompany.Data;
using ITCompany.Models;

namespace ITCompany.Controllers
{
    public class TasksController : Controller
    {
        private readonly ITCompanyContext _context;

        public TasksController(ITCompanyContext context)
        {
            _context = context;
        }

        // GET: Tasks
        public async Task<IActionResult> Index()
        {
            var iTCompanyContext = _context.Tasks.Include(t => t.Project);
            return View(await iTCompanyContext.ToListAsync());
        }

        // GET: Tasks/Details/5
        public async Task<IActionResult> Details(int? id)
        { 
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Tasks
                .Include(t => t.Project)
                .Include(t => t.TaskCommands)
                .FirstOrDefaultAsync(m => m.ID == id);

            var currentUser = _context.Users.First(x => x.Login.Equals(HttpContext.User.Identity.Name));

            ViewBag.isPrime = false;
            var project = _context.Projects.Include(x=>x.ProjectCommands).First(x=>x.ID == task.ProjectID);


            foreach (ProjectCommand pc in project.ProjectCommands)
            {
                pc.Employee = _context.Users.Include(x => x.Role).First(x => x.ID == pc.EmployeeID);
                if (pc.EmployeeID == currentUser.ID && pc.isPrime)
                    ViewBag.isPrime = true;

            }

            foreach (TaskCommand tc in task.TaskCommands)
            {
                tc.Employee = _context.Users.Include(x=>x.Role).First(x=>x.ID == tc.EmployeeID);
            }
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        // GET: Tasks/Create
        public IActionResult Create(int? id)
        {
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID",(int)id);
            return View();
        }

        public IActionResult Finish(int? id)
        {
            var task = _context.Tasks.Include(x => x.Project).Include(x => x.Project.Tasks).First(x => x.ID == (int)id);

            task.FactDate = DateTime.Now;

            _context.Tasks.Update(task);
            _context.SaveChanges();

            var project = task.Project;
            project.Percent = (int)(((double)project.Tasks.Where(x=>x.FactDate.ToString() != "01.01.0001 0:00:00").Count() / (double)project.Tasks.Count() ) * 100);

            if (project.Percent == 100)
                project.EndDate = DateTime.Now;

            _context.Projects.Update(project);
            _context.SaveChanges();

            return Redirect("/Projects/Details/"+project.ID);
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,StartDate,EndDate,Description,Coeffecient,ProjectID")] ITCompany.Models.Task task)
        {
            if (ModelState.IsValid)
            {
                _context.Add(task);
                await _context.SaveChangesAsync();

                var task2 = _context.Tasks.Include(x=>x.Project).Include(x => x.Project.Tasks).First(x=>x.ID == task.ID);

                var project = task2.Project;
                
                project.Percent = (int)(((double)project.Tasks.Where(x => x.FactDate.ToString() != "01.01.0001 0:00:00").Count() / (double)project.Tasks.Count()) * 100);

                _context.Projects.Update(project);
                await _context.SaveChangesAsync();

                return Redirect("/Projects/Details/"+task.ProjectID);
            }
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID", task.ProjectID);
            return View(task);
        }

        // GET: Tasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Tasks.FindAsync(id);
            if (task == null)
            {
                return NotFound();
            }
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID", task.ProjectID);
            return View(task);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,StartDate,EndDate,FactDate,Description,Coeffecient,ProjectID")] ITCompany.Models.Task task)
        {
            if (id != task.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(task);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskExists(task.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID", task.ProjectID);
            return View(task);
        }

        // GET: Tasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Tasks
                .Include(t => t.Project)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var task = await _context.Tasks.FindAsync(id);
            _context.Tasks.Remove(task);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TaskExists(int id)
        {
            return _context.Tasks.Any(e => e.ID == id);
        }
    }
}

ITCompany/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ITCompany.Data;
using ITCompany.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace ITCompany.Controllers
{
    public class UsersController : Controller
    {
        private readonly ITCompanyContext _context;
        private IHostingEnvironment Environment;

        public UsersController(ITCompanyContext context, IHostingEnvironment _environment)
        {
            _context = context;
            Environment = _environment;        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            var iTCompanyContext = _context.Users.Include(u => u.Role);
            return View(await iTCompanyContext.ToListAsync());
        } 


        // GET: Clients
        public async Task<IActionResult> Clients()
        {
            var iTCompanyContext = _context.Users.Include(u => u.Role).Where(x=>x.RoleID == _context.Roles.First(x=>x.Name.Equals("Клієнт")).ID);
            return View("Index", await iTCompanyContext.ToListAsync());
        }
        // GET: Employees
        public async Task<IActionResult> Employees()
        {
            var iTCompanyContext = _context.Users.Include(u => u.Role).Where(x => x.RoleID != _context.Roles.First(x => x.Name.Equals("Клієнт")).ID);
            return View("Index", await iTCompanyContext.ToListAsync());
        }


        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                ViewBag.My = true;
                var currentUser = _context.Users
                    .Include(x => x.Role)
                    .Include(x => x.Projects)
                    .Include(u => u.ProjectCommands)
                    .Include(x => x.TaskCommands)
                    .First(x => x.Login.Equals(HttpContext.User.Identity.Name));
                foreach (Project p in currentUser.Projects)
                {
                    p.ProjectType = _context.ProjectTypes.First(x => x.ID == p.ProjectTypeID);
                }
                foreach (ProjectCommand pc in currentUser.ProjectCommands)
                {
                    pc.Project = _context.Projects.Include(x=>x.ProjectType).Include(x => x.Tasks).Include(x=>x.ProjectCommands).First(x => x.ID == pc.ProjectID);
                }
                foreach (TaskCommand tc in currentUser.TaskCommands)
                {
                    tc.Task = _context.Tasks.Include(x => x.Project).First(x => x.ID == tc.TaskID);
                }

                return View(currentUser);
            }

            ViewBag.My = false;
            var user = await _context.Users
                .Include(u => u.Role)
                .Include(x => x.Projects)
                    .Include(u => u.ProjectCommands)
                    .Include(x => x.TaskCommands)
                .FirstOrDefaultAsync(m => m.ID == id);

            foreach (Project p in user.Projects)
            {
                p.ProjectType = _context.ProjectTypes.First(x => x.ID == p.ProjectTypeID);
            }
            foreach (ProjectCommand pc in user.ProjectCommands)
            {
                pc.Project = _context.Projects.Include(x => x.ProjectType).Include(x=>x.Tasks).Include(x => x.ProjectCommands).First(x => x.ID == pc.ProjectID);
            }
            foreach (TaskCommand tc in user.TaskCommands)
            {
                tc.Task = _context.Tasks.Include(x=>x.Project).First(x => x.ID == tc.TaskID);
            }

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            ViewData["RoleID"] = new SelectList(_context.Roles, "ID", "Name");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Login,Password,FirstName,LastName,RoleID")] User user, IFormFile file)
        {

            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();

                string wwwPath = this.Environment.WebRootPath;
                string contentPath = this.Environment.ContentRootPath;

                User user2 = _context.Users.First(x => x.Login.Equals(user.Login));

                string path = Path.Combine(this.Environment.WebRootPath, "Images/Users/" + user2.ID);
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                string fileName = Path.GetFileName(file.FileName);
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                user2.Avatar = "/Images/Users/" + user2.ID + "/" + fileName;

                _context.Users.Update(user2);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleID"] = new SelectList(_context.Roles, "ID", "Name", user.RoleID);
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["RoleID"] = new SelectList(_context.Roles, "ID", "Name", user.RoleID);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Login,Password,FirstName,LastName,Avatar,RoleID")] User user, IFormFile file)
        {
            if (id != user.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        string wwwPath = this.Environment.WebRootPath;
                        string contentPath = this.Environment.ContentRootPath;

                        string path = Path.Combine(this.Environment.WebRootPath, "Images/Users/" + user.ID);
                        if (!Directory.Exists(path))
                        {
                            Directory.CreateDirectory(path);
                        }

                        string fileName = Path.GetFileName(file.FileName);
                        using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                        {
                            file.CopyTo(stream);
                        }

                        user.Avatar = "/Images/Users/" + user.ID + "/" + fileName;
                    }
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect("~/Users/Details/" + user.ID);
            }
            ViewData["RoleID"] = new SelectList(_context.Roles, "ID", "Name", user.RoleID);
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.ID == id);
        }
    }
}

ITCompany/Views/Tasks/Create.cshtml
@model ITCompany.Models.Task

@{
    ViewData["Title"] = "Create";
}

<h1>Додати</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Назва</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">Дата початку</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">Дата закінчення</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="FactDate" class="control-label"></label>
                <input asp-for="FactDate" class="form-control" />
                <span asp-validation-for="FactDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Опис</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Coeffecient" class="control-label">Коефіціент складності завдання</label>
                <input asp-for="Coeffecient" class="form-control" />
                <span asp-validation-for="Coeffecient" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="ProjectID" class="control-label"></label>
                <select asp-for="ProjectID" class ="form-control" asp-items="ViewBag.ProjectID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Створити завдання" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ITCompany/Views/Tasks/Delete.cshtml
@model ITCompany.Models.Task

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Назва
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Дата початку
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            Дата закінчення
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            Фактична дата закінчення завдання
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FactDate)
        </dd>
        <dt class = "col-sm-2">
            Опис
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            Коефіцієнт складності завдання
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Coeffecient)
        </dd>
        <dt class = "col-sm-2">
            Проєкт
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.ID)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        
    </form>
</div>

ITCompany/Views/Tasks/Details.cshtml
@model ITCompany.Models.Task

@{
    ViewData["Title"] = "Details";
}

<h1>Інформація</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Назва
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Дата початку
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            Дата закінчення
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            Фактична дата закінчення
        </dt>
        @if(Model.FactDate.ToString()!="01.01.0001 0:00:00")
        {
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.FactDate)
            </dd>
        }
        else
        {
            <dd class = "col-sm-10">
                @Html.Raw("-")
            </dd>
        }
        <dt class = "col-sm-2">
            Опис
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            Коефіцієнт складності
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Coeffecient)
        </dd>
        <dt class = "col-sm-2">
            Проєкт
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
    </dl>
</div>
<div>
    @if(Model.FactDate.ToString()=="01.01.0001 0:00:00" && !User.IsInRole("Клієнт") || ViewBag.isPrime)
    {
        <p>
            <a style="color: red;" asp-controller="Tasks" asp-action="Finish" asp-route-id="@Model.ID">Завершити завдання</a> 
        </p>
        <hr />
        <p>
            <a asp-controller="TaskCommands" asp-action="Create" asp-route-id="@Model.ID">Додати працівника на завдання</a> 
        </p>
    }
</div>
<div>
    @if (Model.TaskCommands.Count() > 0)
    {
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>
                        
                    </th>
                    <th>
                        Працівник
                    </th>
                    <th>
                        Посада
                    </th>
                </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.TaskCommands) {
                <tr>
                    <td>
                        <a asp-controller="Users" asp-action="Details" asp-route-id="@item.Employee.ID"><img src="@item.Employee.Avatar" alt="avatar" width="150px;"/></a> 
                    </td>
                    <td>
                        <a asp-controller="Users" asp-action="Details" asp-route-id="@item.Employee.ID">@Html.DisplayFor(modelItem => item.Employee.FullName)</a> 
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Employee.Role.Name)
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
</div>

ITCompany/Views/Tasks/Edit.cshtml
@model ITCompany.Models.Task

@{
    ViewData["Title"] = "Edit";
}

<h1>Редагувати</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Назва</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">Дата початку</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">Дата закінчення</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FactDate" class="control-label"></label>
                <input asp-for="FactDate" class="form-control" />
                <span asp-validation-for="FactDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Опис</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Coeffecient" class="control-label">Коефіціент складності завдання</label>
                <input asp-for="Coeffecient" class="form-control" />
                <span asp-validation-for="Coeffecient" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectID" class="control-label"></label>
                <select asp-for="ProjectID" class="form-control" asp-items="ViewBag.ProjectID"></select>
                <span asp-validation-for="ProjectID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ITCompany/Views/Tasks/Index.cshtml
@model IEnumerable<ITCompany.Models.Task>

@{
    ViewData["Title"] = "Index";
}



<p>
    <a asp-action="Create">Додати</a>
</p>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                Назва
            </th>
            <th>
                Дата початку
            </th>
            <th>
                Дата закінчення
            </th>
            <th>
                Фактична дата закінчення завдання
            </th>
            <th>
                Опис
            </th>
            <th>
                Коефіцієнт складності завдання
            </th>
            <th>
                Проєкт
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FactDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Coeffecient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.ID)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Редагувати</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Інформація</a> 
                
            </td>
        </tr>
}
    </tbody>
</table>