ITCompany/Models/Project.cs
using System;
using System.Collections.Generic;

namespace ITCompany.Models
{
    public class Project
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int Price { get; set; }
        public int ProjectTypeID { get; set; }
        public int Percent { get; set; }
        public int ClientID { get; set; }
        public User Client { get; set; }
        public ProjectType ProjectType { get; set; }
        public ICollection<Task> Tasks { get; set; }
        public ICollection<ProjectCommand> ProjectCommands { get; set; }

    }
}

ITCompany/Models/ProjectType.cs
using System.Collections.Generic;

namespace ITCompany.Models
{
    public class ProjectType
    {
        public int ID { get; set; }
        public string Name { get; set; }
        ICollection<Project> Projects { get; set; }
    }
}

ITCompany/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ITCompany.Data;
using ITCompany.Models;

namespace ITCompany.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ITCompanyContext _context;

        public ProjectsController(ITCompanyContext context)
        {
            _context = context;
        }

        // GET: Projects
        public async Task<IActionResult> Index()
        {
            var iTCompanyContext = _context.Projects.Include(p => p.ProjectType).Include(x=>x.ProjectCommands).Include(x => x.Tasks);
            return View(await iTCompanyContext.ToListAsync()); 
        }

        public async Task<IActionResult> MyProjects()
        {
            var currentUser = _context.Users.Include(x=>x.Role).First(x => x.Login.Equals(HttpContext.User.Identity.Name));
            if (currentUser.Role.Name.Equals("Клієнт"))
            {
                var iTCompanyContext = _context.Projects.Include(p => p.ProjectType).Include(x => x.ProjectCommands).Include(x => x.Tasks).Where(x => x.ClientID == currentUser.ID);
                return View("Index", await iTCompanyContext.ToListAsync());
            }
            else
            {
                var iTCompanyContext = _context.Projects.Include(x=>x.ProjectCommands).Include(p => p.ProjectType).Include(x => x.ProjectCommands).Include(x => x.Tasks).Where(x => x.ProjectCommands.Select(x=>x.EmployeeID).Contains(currentUser.ID));
                return View("Index", await iTCompanyContext.ToListAsync());
            }
            
        }

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(p => p.ProjectType)
                .Include(p => p.ProjectCommands)
                .Include(p => p.Tasks)
                .FirstOrDefaultAsync(m => m.ID == id);


            var currentUser = _context.Users.First(x => x.Login.Equals(HttpContext.User.Identity.Name));

            ViewBag.isPrime = false; 
            if(project.ProjectCommands.FirstOrDefault(x=>x.EmployeeID == currentUser.ID) != null)
            {
                ViewBag.isPrime = project.ProjectCommands.FirstOrDefault(x => x.EmployeeID == currentUser.ID).isPrime;
            }

            foreach(ProjectCommand pc in project.ProjectCommands)
            {
                pc.Employee = _context.Users.Include(x=>x.Role).First(x=>x.ID == pc.EmployeeID);
            }



            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        public async Task<IActionResult> Accept(int? id, DateTime EndDate, int Price)
        {

            var project = await _context.Projects
                .Include(p => p.ProjectType)
                .FirstOrDefaultAsync(m => m.ID == id);

            project.StartDate = DateTime.Now;
            project.EndDate = EndDate;
            project.Price = Price;

            _context.Projects.Update(project);
            _context.SaveChanges();
            return Redirect("/Projects/Details/"+project.ID);
        }

        public async Task<IActionResult> Reject(int? id)
        {

            var project = await _context.Projects
                .Include(p => p.ProjectType)
                .FirstOrDefaultAsync(m => m.ID == id);

            project.StartDate = DateTime.Now;
            project.EndDate = DateTime.Now;

            _context.Projects.Update(project);
            _context.SaveChanges();
            return Redirect("/Projects/Details/" + project.ID);
        }

        // GET: Projects/Create
        public IActionResult Create()
        {
            ViewData["ProjectTypeID"] = new SelectList(_context.ProjectTypes, "ID", "Name");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Description,Price,ProjectTypeID")] Project project)
        {
            if (ModelState.IsValid)
            {
                var currentUser = _context.Users.First(x => x.Login.Equals(HttpContext.User.Identity.Name));
                project.ClientID = currentUser.ID;
                _context.Add(project);
                await _context.SaveChangesAsync();
                return Redirect("/Projects/MyProjects");
            }
            ViewData["ProjectTypeID"] = new SelectList(_context.ProjectTypes, "ID", "ID", project.ProjectTypeID);
            return View(project);
        }

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FindAsync(id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["ProjectTypeID"] = new SelectList(_context.ProjectTypes, "ID", "Name", project.ProjectTypeID);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Description,StartDate,EndDate,Price,ProjectTypeID")] Project project)
        {
            if (id != project.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var currentUser = _context.Users.Include(x => x.Role).First(x => x.Login.Equals(HttpContext.User.Identity.Name));

                    project.Client = currentUser;
                    project.ClientID = currentUser.ID;

                    _context.Projects.Update(project);
                    
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProjectExists(project.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectTypeID"] = new SelectList(_context.ProjectTypes, "ID", "ID", project.ProjectTypeID);
            return View(project);
        }

        // GET: Projects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(p => p.ProjectType)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var project = await _context.Projects.FindAsync(id);
            _context.Projects.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProjectExists(int id)
        {
            return _context.Projects.Any(e => e.ID == id);
        }
    }
}

ITCompany/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ITCompany.Data;
using ITCompany.Models;

namespace ITCompany.Controllers
{
    public class TasksController : Controller
    {
        private readonly ITCompanyContext _context;

        public TasksController(ITCompanyContext context)
        {
            _context = context;
        }

        // GET: Tasks
        public async Task<IActionResult> Index()
        {
            var iTCompanyContext = _context.Tasks.Include(t => t.Project);
            return View(await iTCompanyContext.ToListAsync());
        }

        // GET: Tasks/Details/5
        public async Task<IActionResult> Details(int? id)
        { 
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Tasks
                .Include(t => t.Project)
                .Include(t => t.TaskCommands)
                .FirstOrDefaultAsync(m => m.ID == id);

            var currentUser = _context.Users.First(x => x.Login.Equals(HttpContext.User.Identity.Name));

            ViewBag.isPrime = false;
            var project = _context.Projects.Include(x=>x.ProjectCommands).First(x=>x.ID == task.ProjectID);


            foreach (ProjectCommand pc in project.ProjectCommands)
            {
                pc.Employee = _context.Users.Include(x => x.Role).First(x => x.ID == pc.EmployeeID);
                if (pc.EmployeeID == currentUser.ID && pc.isPrime)
                    ViewBag.isPrime = true;

            }

            foreach (TaskCommand tc in task.TaskCommands)
            {
                tc.Employee = _context.Users.Include(x=>x.Role).First(x=>x.ID == tc.EmployeeID);
            }
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        // GET: Tasks/Create
        public IActionResult Create(int? id)
        {
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID",(int)id);
            return View();
        }

        public IActionResult Finish(int? id)
        {
            var task = _context.Tasks.Include(x => x.Project).Include(x => x.Project.Tasks).First(x => x.ID == (int)id);

            task.FactDate = DateTime.Now;

            _context.Tasks.Update(task);
            _context.SaveChanges();

            var project = task.Project;
            project.Percent = (int)(((double)project.Tasks.Where(x=>x.FactDate.ToString() != "01.01.0001 0:00:00").Count() / (double)project.Tasks.Count() ) * 100);

            if (project.Percent == 100)
                project.EndDate = DateTime.Now;

            _context.Projects.Update(project);
            _context.SaveChanges();

            return Redirect("/Projects/Details/"+project.ID);
        }

        // POST: Tasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,StartDate,EndDate,Description,Coeffecient,ProjectID")] ITCompany.Models.Task task)
        {
            if (ModelState.IsValid)
            {
                _context.Add(task);
                await _context.SaveChangesAsync();

                var task2 = _context.Tasks.Include(x=>x.Project).Include(x => x.Project.Tasks).First(x=>x.ID == task.ID);

                var project = task2.Project;
                
                project.Percent = (int)(((double)project.Tasks.Where(x => x.FactDate.ToString() != "01.01.0001 0:00:00").Count() / (double)project.Tasks.Count()) * 100);

                _context.Projects.Update(project);
                await _context.SaveChangesAsync();

                return Redirect("/Projects/Details/"+task.ProjectID);
            }
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID", task.ProjectID);
            return View(task);
        }

        // GET: Tasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Tasks.FindAsync(id);
            if (task == null)
            {
                return NotFound();
            }
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID", task.ProjectID);
            return View(task);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,StartDate,EndDate,FactDate,Description,Coeffecient,ProjectID")] ITCompany.Models.Task task)
        {
            if (id != task.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(task);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskExists(task.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID", task.ProjectID);
            return View(task);
        }

        // GET: Tasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var task = await _context.Tasks
                .Include(t => t.Project)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (task == null)
            {
                return NotFound();
            }

            return View(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var task = await _context.Tasks.FindAsync(id);
            _context.Tasks.Remove(task);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TaskExists(int id)
        {
            return _context.Tasks.Any(e => e.ID == id);
        }
    }
}

ITCompany/Views/Projects/Create.cshtml
@model ITCompany.Models.Project

@{
    ViewData["Title"] = "Create";
}

<h1>Додати</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Назва</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Опис</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="StartDate" class="control-label">Дата початку</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="EndDate" class="control-label">Дата закінчення</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Ціна</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectTypeID" class="control-label">Тип проекту</label>
                <select asp-for="ProjectTypeID" class ="form-control" asp-items="ViewBag.ProjectTypeID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ITCompany/Views/Projects/Delete.cshtml
@model ITCompany.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Назва
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Опис
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            Дата початку
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            Дата закінчення
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            Вартість
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            Тип проекту
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectType.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        
    </form>
</div>

ITCompany/Views/Projects/Details.cshtml
@model ITCompany.Models.Project

@{
    ViewData["Title"] = "Details";
}

<h1>Інформація</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Назва
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Опис
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            Дата початку
        </dt>
        @if(Model.StartDate.ToString() != "01.01.0001 0:00:00"){
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.StartDate)
            </dd>
        }
        else{
            <dd class = "col-sm-10">
                @Html.Raw("-")
            </dd>
        }
        <dt class = "col-sm-2">
            Дата закінчення
        </dt>
        @if(Model.EndDate.ToString() != "01.01.0001 0:00:00"){
            <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.EndDate)
            </dd>
        }
        else{
            <dd class = "col-sm-10">
                @Html.Raw("-")
            </dd>
        }
        <dt class = "col-sm-2">
            Вартість
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            Тип проекту
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProjectType.Name)
        </dd>
    </dl>
</div>
<div>
    @if(Model.StartDate.ToString() == "01.01.0001 0:00:00") {

        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Accept">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ID" />
                    @if (User.IsInRole("Директор"))
                    {
                        <div class="form-group">
                            <label asp-for="EndDate" class="control-label">Дата закінчення</label>
                            <input asp-for="EndDate" class="form-control" />
                            <span asp-validation-for="EndDate" class="text-danger"></span>
                        </div>
                    }
                    <div class="form-group">
                        <label asp-for="Price" class="control-label">Ціна</label>
                        <input asp-for="Price" class="form-control" />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Прийняти" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    }
    @if (Model.StartDate.ToString() == "01.01.0001 0:00:00")
    {
        <p>
            <a style="color:red;" asp-controller="Projects" asp-action="Reject" asp-route-id="@Model.ID">Відхилити</a>
        </p>
    }
    @*todo add functional for isPrimeUser*@
    else if(!User.IsInRole("Клієнт") && ((Model.EndDate.CompareTo(DateTime.Now)>0) || ViewBag.isPrime)){
        <p>
            <a asp-controller="ProjectCommands" asp-action="Create" asp-route-id="@Model.ID">Додати члена команды</a>
        </p>
        if (ViewBag.isPrime)
        {
            <p>
                <a asp-controller="Tasks" asp-action="Create" asp-route-id="@Model.ID">Додати задачу</a>
            </p>
        }
    }
</div>

<div>
    @if(Model.Tasks.Count() > 0)
    {   
        <h5>Завдання</h5>
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>
                        Назва
                    </th>
                    <th>
                        Дата початку
                    </th>
                    <th>
                        Дата закінчення
                    </th>
                    <th>
                        Фактична дата закінчення
                    </th>
                    <th>
                        Опис
                    </th>
                    <th>
                        Коефіцієнт складності
                    </th>
                </tr>
            </thead>
            <tbody>
        @foreach (var item in Model.Tasks) {
                <tr>
                    <td>
                        <a asp-controller="Tasks" asp-action="Details" asp-route-id="@item.ID">@Html.DisplayFor(modelItem => item.Name)</a> 
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDate)
                    </td>
                        @if(item.FactDate.ToString() != "01.01.0001 0:00:00")
                        {
                            <td>
                                @Html.DisplayFor(modelItem => item.FactDate)
                            </td>
                        }
                        else
                        {
                            <td>
                                @Html.Raw("-")
                            </td>
                        }
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Coeffecient)
                    </td>
                </tr>
        }
            </tbody>
        </table>
    }
</div>

<div>
    @if(Model.ProjectCommands.Count() > 0)
    {
        <h5>Команда</h5>
        <table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>
                
            </th>
            <th>
                Працівник
            </th>
            <th>
                
            </th>
            <th>
                Головний?
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.ProjectCommands) {
        <tr>
            <td>
                <a asp-controller="Users" asp-action="Details" asp-route-id="@item.Employee.ID"><img src="@item.Employee.Avatar" alt="avatar" width="150px;"/></a> 
            </td>
            <td>
                <a asp-controller="Users" asp-action="Details" asp-route-id="@item.Employee.ID">@Html.DisplayFor(modelItem => item.Employee.FullName)</a> 
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.Role.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isPrime)
            </td>
        </tr>
}
    </tbody>
</table>
    }
</div>

ITCompany/Views/Projects/Edit.cshtml
@model ITCompany.Models.Project

@{
    ViewData["Title"] = "Edit";
}

<h1>Редагувати</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Назва</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Опис</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @if(User.IsInRole("Директор")){
                <div class="form-group">
                    <label asp-for="StartDate" class="control-label">Дата початку</label>
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EndDate" class="control-label">Дата закінчення</label>
                    <input asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
            }
            else{
                <div class="form-group" hidden>
                    <label asp-for="StartDate" class="control-label">Дата початку</label>
                    <input asp-for="StartDate" class="form-control" />
                    <span asp-validation-for="StartDate" class="text-danger"></span>
                </div>
                <div class="form-group" hidden>
                    <label asp-for="EndDate" class="control-label">Дата закінчення</label>
                    <input asp-for="EndDate" class="form-control" />
                    <span asp-validation-for="EndDate" class="text-danger"></span>
                </div>
            }
            
            <div class="form-group">
                <label asp-for="Price" class="control-label">Ціна</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectTypeID" class="control-label">Тип проекту</label>
                <select asp-for="ProjectTypeID" class="form-control" asp-items="ViewBag.ProjectTypeID"></select>
                <span asp-validation-for="ProjectTypeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}